travis:
  secure:
    BINSTAR_TOKEN: g5tGrBPAX4zEtlQnopBd+3UP59O2/PjPQPJysJ0rOAhVi8kXQ/VrGsMXjqGR4tYJSw5c4b154VXd5sN5PwNP+5J0dnKJE1A3sdgdrJOcjL8cDI5QUpeFpij/lDSafVsftN7pBOsDF+MRf7gId+UdOrKkRd5h2aodcVea3cENx+fHQNPgLhKLGBB0Kp0mnmcL3cM/QSJ1cNVZGbCy23UBKwNEwn/Z1uOShiqqEtBnpvWNo1WIOGEuv++NsE8rL3EEbvoNFGpZLzx2IOgurAVoC9yq/E6U8Orup/9FTvaPOlG+RLWBZm3h0FZGDoR9gz6HlZrGmQl8Hf5KpOEWl4aHEQrJCItr7K3qQQjPiPBHGZEfC2HZnguKTtCws77X8O8ziFilt1xqY7ekl78ZrKLj3hWeIf905JKkjzajRa2OTr+iGf9ADvq/axsjGq0okUWRfEGEJrG79zNW0JkFRm1CiIg+WnyaETFNbH5q8R8eUVic28B3rb/IqHGtJRtLYIr2AhL47qux6JvhzFV+7XH/WnuO6uNEilYDvebs37/5N4mcb+CNaXVvQOMMO3twY4r4G6xZYNJaWr2hXZePVgEQIKZ5bkCDvhCjLfiIafv+WQpJZGAPi5S5jiAVtc1nI34IS7h2+SnltpHYa4xUpSnRv8zN8tv0hHZOItIW/xwwoGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
